---
- name: License BIG-IP using default license options
  bigip_license:
    user: "{{ username }}"
    password: "{{ password }}"
    server: "{{ inventory_hostname }}"
    key: "{{ key }}"
    validate_certs: "no"
  delegate_to: localhost
...
