---
- name: Add a new node
  bigip_node:
    server: "{{ inventory_hostname }}"
    user: "{{ username }}"
    password: "{{ password }}"
    host: "{{ host  }}"
    name: "{{ name }}"
    validate_certs: "false"
    state: "{{ state }}"
    availabiltiy_requirement: "all"
    monitors:
      - "{{ monitor }}"
  delegate_to: localhost
...
